[package]
edition = "2021"
name = "azalea-inventory"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azalea-core = { version = "0.5.0", path = "../azalea-core" }
azalea-inventory-macros = { version = "0.1.0", path = "./azalea-inventory-macros" }
