[package]
description = "Representations of various inventory data structures in Minecraft."
edition = "2021"
license = "MIT"
name = "azalea-inventory"
repository = "https://github.com/azalea-rs/azalea/tree/main/azalea-inventory-macros"
version = "0.8.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azalea-buf = { version = "0.8.0", path = "../azalea-buf" }
azalea-inventory-macros = { version = "0.8.0", path = "./azalea-inventory-macros" }
simdnbt = { version = "0.2.1" }
azalea-registry = { version = "0.8.0", path = "../azalea-registry" }
