[package]
description = "Representations of various inventory data structures in Minecraft."
edition = "2021"
license = "MIT"
name = "azalea-inventory"
repository = "https://github.com/azalea-rs/azalea/tree/main/azalea-inventory-macros"
version = "0.9.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simdnbt = { version = "0.4", git = "https://github.com/azalea-rs/simdnbt" }
azalea-buf = { version = "0.9.1", path = "../azalea-buf" }
azalea-inventory-macros = { version = "0.9.1", path = "./azalea-inventory-macros" }
azalea-registry = { version = "0.9.1", path = "../azalea-registry" }
azalea-chat = { version = "0.9.1", path = "../azalea-chat" }
azalea-core = { version = "0.9.1", path = "../azalea-core" }
uuid = "1.8.0"
