[package]
description = "Translate Minecraft strings from their id."
edition = "2021"
license = "MIT"
name = "azalea-language"
repository = "https://github.com/mat-1/azalea/tree/main/azalea-language"
version = "0.6.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.16.0"
serde = "1.0.137"
serde_json = "1.0.81"
# tokio = {version = "^1.21.2", features = ["fs"]}
