[package]
description = "Representation of Minecraft block states."
edition = "2021"
license = "MIT"
name = "azalea-block"
repository = "https://github.com/mat-1/azalea/tree/main/azalea-block"
version = "0.6.0"

[lib]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azalea-block-macros = { path = "./azalea-block-macros", version = "^0.6.0" }
azalea-buf = { path = "../azalea-buf", version = "^0.6.0" }
azalea-registry = { version = "0.6.0", path = "../azalea-registry" }
