[package]
description = "Representation of Minecraft block states."
edition = "2021"
license = "MIT"
name = "azalea-block"
version = "0.1.0"

[lib]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azalea-block-macros = {path = "./azalea-block-macros", version = "^0.1.0"}
azalea-buf = {path = "../azalea-buf", version = "^0.2.0" }
