[package]
edition = "2021"
name = "azalea-nbt"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.0"
azalea-buf = {path = "../azalea-buf"}
byteorder = "1.4.3"
flate2 = "1.0.23"
num-derive = "^0.3.3"
num-traits = "^0.2.14"

[dev-dependencies]
criterion = {version = "^0.3.5", features = ["html_reports"]}

[profile.release]
lto = true

[profile.bench]
debug = true

[[bench]]
harness = false
name = "my_benchmark"
