[package]
edition = "2021"
name = "azalea-physics"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azalea-block = {path = "../azalea-block"}
azalea-core = {path = "../azalea-core"}
azalea-entity = {path = "../azalea-entity"}
azalea-world = {path = "../azalea-world"}
