[package]
description = "Physics for Minecraft entities."
edition = "2021"
license = "MIT"
name = "azalea-physics"
repository = "https://github.com/azalea-rs/azalea/tree/main/azalea-physics"
version = "0.8.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azalea-block = { path = "../azalea-block", version = "0.8.0" }
azalea-core = { path = "../azalea-core", version = "0.8.0" }
azalea-entity = { version = "0.8.0", path = "../azalea-entity" }
azalea-inventory = { version = "0.8.0", path = "../azalea-inventory" }
azalea-registry = { path = "../azalea-registry", version = "0.8.0" }
azalea-world = { path = "../azalea-world", version = "0.8.0" }
bevy_app = "0.12.0"
bevy_ecs = "0.12.0"
tracing = "0.1.40"
once_cell = "1.18.0"
parking_lot = "^0.12.1"

[dev-dependencies]
bevy_time = "0.12.0"
uuid = "^1.5.0"
