[package]
description = "Use Minecraft's registries."
edition = "2021"
license = "MIT"
name = "azalea-registry"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azalea-buf = {path = "../azalea-buf", version = "^0.2.0" }
azalea-registry-macros = {path = "./azalea-registry-macros", version = "^0.1.0"}
