[package]
description = "Use Minecraft's registries."
edition = "2021"
license = "MIT"
name = "azalea-registry"
repository = "https://github.com/azalea-rs/azalea/tree/main/azalea-registry"
version = "0.10.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simdnbt = { version = "0.5", git = "https://github.com/azalea-rs/simdnbt" }
azalea-buf = { path = "../azalea-buf", version = "0.10.0" }
azalea-registry-macros = { path = "./azalea-registry-macros", version = "0.10.0" }
once_cell = "1.19.0"
[features]
serde = ["azalea-registry-macros/serde"]
default = ["serde"]
