[package]
description = "Use Minecraft's registries."
edition = "2021"
license = "MIT"
name = "azalea-registry"
repository = "https://github.com/mat-1/azalea/tree/main/azalea-registry"
version = "0.6.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azalea-buf = {path = "../azalea-buf", version = "^0.6.0" }
azalea-registry-macros = {path = "./azalea-registry-macros", version = "^0.6.0" }
enum-as-inner = "0.5.1"
