[package]
edition = "2021"
name = "buf-macros"
version = "0.1.0"

[lib]
proc-macro = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "^1.0.36"
quote = "^1.0.10"
syn = "^1.0.82"
