[package]
name = "azalea-core"
description = "Miscellaneous things in Azalea."
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
azalea-buf = { path = "../azalea-buf", version = "0.11.0" }
azalea-registry = { path = "../azalea-registry", version = "0.11.0" }
bevy_ecs = { workspace = true, optional = true }
nohash-hasher = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true, optional = true }
#serde_json = { workspace = true }
simdnbt = { workspace = true }
tracing = { workspace = true }
#uuid = { workspace = true }

[features]
bevy_ecs = ["dep:bevy_ecs"]
serde = ["dep:serde"]
strict_registry = []
