[package]
description = "Miscellaneous things in Azalea."
edition = "2021"
license = "MIT"
name = "azalea-core"
repository = "https://github.com/azalea-rs/azalea/tree/main/azalea-core"
version = "0.10.3+mc1.21.4"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azalea-buf = { path = "../azalea-buf", version = "0.10.0" }
azalea-registry = { path = "../azalea-registry", version = "0.10.0" }
bevy_ecs = { workspace = true, optional = true }
nohash-hasher = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true, optional = true }
#serde_json = { workspace = true }
simdnbt = { workspace = true }
tracing = { workspace = true }
#uuid = { workspace = true }

[features]
bevy_ecs = ["dep:bevy_ecs"]
serde = ["dep:serde"]
strict_registry = []
