on:
  push:
  pull_request:
    types: [opened, reopened]

env:
  CARGO_INCREMENTAL: 0 # required so ci doesn't run out of space
  CARGO_TERM_COLOR: always

name: Cargo clippy & test
jobs:
  clippy_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nightly
        run: rustup update nightly && rustup default nightly && rustup component add clippy

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Clippy
        run: cargo clippy --all-features

      - name: Test
        run: cargo test
